### PR TITLE
Chapter 6 Exercises

### PR DESCRIPTION
**Pull request by alotofwe**
# Exercises

1. Add a test for the email downcasing from Listing 6.31, as shown in Listing 6.41. This test uses the reload method for reloading a value from the database and the assert_equal method for testing equality. 2. To verify that Listing 6.41 tests the right thing, comment out the before_save line to get to red, then uncomment it to get to green.
By running the test suite, verify that the before_save callback can be written using the “bang” method email.downcase! to modify the email attribute directly, as shown in Listing 6.42.
3. As noted in Section 6.2.4, the email regex in Listing 6.21 allows invalid email addresses with consecutive dots in the domain name, i.e., addresses of the form foo@bar..com. Add this address to the list of invalid addresses in Listing 6.19 to get a failing test, and then use the more complicated regex shown in Listing 6.43 to get the test to pass.

## 1

Listing 6.41のテストをぺたりとペーストする

## 2

bangに書き換えるだけ
破壊的メソッド

## 3

まずテストの不正なURLに指示されたものを加え，落ちることを確認した  
その後チェックを強化し，greenなことを確認

# Close条件

1人に良い感じをもらう

### CODE REVIEW

**Comment by alotofwe** [comment]
byebug (bug)

**Comment by alotofwe** [comment]
masterのも直そう

**Comment by Joe-noh** [comment]
よいね

**Comment by alotofwe** [comment]
コピペゲーだった

**Pull request closed without merging**
